/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package evmproject;

import static evmproject.VotingRegistration.s;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;

/**
 *
 * @author Dell
 */
public class PartyDetails extends javax.swing.JFrame {
    String adhr;
    String partyname;
    PreparedStatement ps;
    Connection con;
    ResultSet rs;
    

    /**
     * Creates new form PartyDetails
     */
    public PartyDetails() {
        initComponents();
        adhr=VoterLogin.aadhar;
        acn.setText(adhr);
        try
        {
             Class.forName("com.mysql.jdbc.Driver");
           con=(Connection) DriverManager.getConnection("jdbc:mysql://localhost:3306/EVM","root","chhavi");
        }
        catch(Exception ee)
        {
            System.out.println(ee);
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        bjp = new javax.swing.JButton();
        congress = new javax.swing.JButton();
        aap = new javax.swing.JButton();
        bsp = new javax.swing.JButton();
        jdu = new javax.swing.JButton();
        sp = new javax.swing.JButton();
        ncp = new javax.swing.JButton();
        nota = new javax.swing.JButton();
        label1 = new javax.swing.JLabel();
        acn = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new java.awt.GridLayout(8, 1, 5, 5));

        jLabel1.setFont(new java.awt.Font("Engravers MT", 1, 12)); // NOI18N
        jLabel1.setText("BHARTIYA JANTA PARTY(BJP)");
        jPanel1.add(jLabel1);

        jLabel2.setFont(new java.awt.Font("Engravers MT", 1, 12)); // NOI18N
        jLabel2.setText("CONGRESS");
        jPanel1.add(jLabel2);

        jLabel3.setFont(new java.awt.Font("Engravers MT", 1, 12)); // NOI18N
        jLabel3.setText("AAM AADMI PARTY(AAP)");
        jPanel1.add(jLabel3);

        jLabel4.setFont(new java.awt.Font("Engravers MT", 1, 12)); // NOI18N
        jLabel4.setText("BSP");
        jPanel1.add(jLabel4);

        jLabel5.setFont(new java.awt.Font("Engravers MT", 1, 12)); // NOI18N
        jLabel5.setText("JDU");
        jPanel1.add(jLabel5);

        jLabel6.setFont(new java.awt.Font("Engravers MT", 1, 12)); // NOI18N
        jLabel6.setText("SP");
        jPanel1.add(jLabel6);

        jLabel7.setFont(new java.awt.Font("Engravers MT", 1, 12)); // NOI18N
        jLabel7.setText("NCP");
        jPanel1.add(jLabel7);

        jLabel8.setFont(new java.awt.Font("Engravers MT", 1, 12)); // NOI18N
        jLabel8.setText("NOTA");
        jPanel1.add(jLabel8);

        jPanel2.setLayout(new java.awt.GridLayout(8, 1, 5, 5));

        bjp.setIcon(new javax.swing.ImageIcon(getClass().getResource("/evmproject/bjp.jpg"))); // NOI18N
        bjp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bjpActionPerformed(evt);
            }
        });
        jPanel2.add(bjp);

        congress.setIcon(new javax.swing.ImageIcon(getClass().getResource("/evmproject/congress.jpg"))); // NOI18N
        congress.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                congressActionPerformed(evt);
            }
        });
        jPanel2.add(congress);

        aap.setIcon(new javax.swing.ImageIcon(getClass().getResource("/evmproject/aap.jpg"))); // NOI18N
        aap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aapActionPerformed(evt);
            }
        });
        jPanel2.add(aap);

        bsp.setIcon(new javax.swing.ImageIcon(getClass().getResource("/evmproject/bsp.jpg"))); // NOI18N
        bsp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bspActionPerformed(evt);
            }
        });
        jPanel2.add(bsp);

        jdu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/evmproject/JDU.jpg"))); // NOI18N
        jdu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jduActionPerformed(evt);
            }
        });
        jPanel2.add(jdu);

        sp.setIcon(new javax.swing.ImageIcon(getClass().getResource("/evmproject/SP.jpg"))); // NOI18N
        sp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                spActionPerformed(evt);
            }
        });
        jPanel2.add(sp);

        ncp.setIcon(new javax.swing.ImageIcon(getClass().getResource("/evmproject/NCP.jpg"))); // NOI18N
        ncp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ncpActionPerformed(evt);
            }
        });
        jPanel2.add(ncp);

        nota.setIcon(new javax.swing.ImageIcon(getClass().getResource("/evmproject/nota.jpg"))); // NOI18N
        nota.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                notaActionPerformed(evt);
            }
        });
        jPanel2.add(nota);

        label1.setFont(new java.awt.Font("Engravers MT", 1, 12)); // NOI18N

        acn.setFont(new java.awt.Font("Engravers MT", 1, 12)); // NOI18N
        acn.setText("AADHAR CARD NO.");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 295, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 146, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(48, 48, 48))
            .addGroup(layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(acn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(129, 129, 129))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(81, 81, 81)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 376, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(30, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(acn))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 376, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void congressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_congressActionPerformed
        // TODO add your handling code here:
        try
        {
            partyname="CONGRESS";
            ps=con.prepareStatement("insert into details values(?,?)");
            ps.setString(1,adhr);
            ps.setString(2, partyname);
            ps.executeUpdate();
            JOptionPane.showMessageDialog(null,"THANKS FOR YOUR VALUABLE VOTE");
        }
        catch(Exception ee)
        {
            System.out.println(ee);
        }
    }//GEN-LAST:event_congressActionPerformed

    private void bjpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bjpActionPerformed
        // TODO add your handling code here:
        try
        {
            partyname="BJP";
            ps=con.prepareStatement("insert into details values(?,?)");
            ps.setString(1,adhr);
            ps.setString(2, partyname);
           
            ps.executeUpdate();
            JOptionPane.showMessageDialog(null,"THANKS FOR YOUR VALUABLE VOTE");
        }
        catch(Exception ee)
        {
            System.out.println(ee);
        }
    }//GEN-LAST:event_bjpActionPerformed

    private void aapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aapActionPerformed
        // TODO add your handling code here:
         try
        {
            partyname="AAP";
            ps=con.prepareStatement("insert into details values(?,?)");
            ps.setString(1,adhr);
            ps.setString(2, partyname);
           
            ps.executeUpdate();
            JOptionPane.showMessageDialog(null,"THANKS FOR YOUR VALUABLE VOTE");
        }
        catch(Exception ee)
        {
            System.out.println(ee);
        }
    }//GEN-LAST:event_aapActionPerformed

    private void bspActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bspActionPerformed
        // TODO add your handling code here:
         try
        {
            partyname="BSP";
            ps=con.prepareStatement("insert into details values(?,?)");
            ps.setString(1,adhr);
            ps.setString(2, partyname);
           
            ps.executeUpdate();
            JOptionPane.showMessageDialog(null,"THANKS FOR YOUR VALUABLE VOTE");
        }
        catch(Exception ee)
        {
            System.out.println(ee);
        }
    }//GEN-LAST:event_bspActionPerformed

    private void jduActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jduActionPerformed
        // TODO add your handling code here:
         try
        {
            partyname="JDU";
            ps=con.prepareStatement("insert into details values(?,?)");
            ps.setString(1,adhr);
            ps.setString(2, partyname);
           
            ps.executeUpdate();
            JOptionPane.showMessageDialog(null,"THANKS FOR YOUR VALUABLE VOTE");
        }
        catch(Exception ee)
        {
            System.out.println(ee);
        }
    }//GEN-LAST:event_jduActionPerformed

    private void spActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_spActionPerformed
        // TODO add your handling code here:
         try
        {
            partyname="SP";
            ps=con.prepareStatement("insert into details values(?,?)");
            ps.setString(1,adhr);
            ps.setString(2, partyname);
           
            ps.executeUpdate();
            JOptionPane.showMessageDialog(null,"THANKS FOR YOUR VALUABLE VOTE");
        }
        catch(Exception ee)
        {
            System.out.println(ee);
        }
    }//GEN-LAST:event_spActionPerformed

    private void ncpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ncpActionPerformed
        // TODO add your handling code here:
         try
        {
            partyname="NCP";
            ps=con.prepareStatement("insert into details values(?,?)");
            ps.setString(1,adhr);
            ps.setString(2, partyname);
           
            ps.executeUpdate();
            JOptionPane.showMessageDialog(null,"THANKS FOR YOUR VALUABLE VOTE");
        }
        catch(Exception ee)
        {
            System.out.println(ee);
        }
    }//GEN-LAST:event_ncpActionPerformed

    private void notaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_notaActionPerformed
        // TODO add your handling code here:
         try
        {
            partyname="NOTA";
            ps=con.prepareStatement("insert into details values(?,?)");
            ps.setString(1,adhr);
            ps.setString(2, partyname);
           
            ps.executeUpdate();
            JOptionPane.showMessageDialog(null,"THANKS FOR YOUR VALUABLE VOTE");
        }
        catch(Exception ee)
        {
            System.out.println(ee);
        }
    }//GEN-LAST:event_notaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PartyDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PartyDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PartyDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PartyDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PartyDetails().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton aap;
    private javax.swing.JLabel acn;
    private javax.swing.JButton bjp;
    private javax.swing.JButton bsp;
    private javax.swing.JButton congress;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JButton jdu;
    private javax.swing.JLabel label1;
    private javax.swing.JButton ncp;
    private javax.swing.JButton nota;
    private javax.swing.JButton sp;
    // End of variables declaration//GEN-END:variables
}
